name = "news-aggregator-web"
compatibility_date = "2026-06-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "news-aggregator"
database_id = "c4d7b287-e336-432c-bd93-930a03af7be9"
preview_database_id = "c4d7b287-e336-432c-bd93-930a03af7be9"

[[queues.producers]]
binding = "NEWS_QUEUE"
queue = "news-fetch-queue"

[ai]
binding = "AI"

